class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Role validation
  enum :role, { client: "Client", professional: "Professional", admin: "Admin" }
  
  # Set default role before validation
  before_validation :set_default_role, on: :create

  # Role check methods (also generated by enum, but explicit for clarity)
  def client?
    role == "Client"
  end

  def professional?
    role == "Professional"
  end

  def admin?
    role == "Admin"
  end

  def get_full_name
    if first_name.present? && last_name.present?
      "#{first_name} #{last_name}"
    elsif first_name.present?
      first_name
    else
      email
    end
  end

  def get_initials
    if first_name.present? && last_name.present?
      "#{first_name.first.upcase}#{last_name.first.upcase}"
    elsif first_name.present?
      first_name.first.upcase
    else
      email.first.upcase
    end
  end
  
  private
  
  def set_default_role
    self.role ||= "Client"
  end
end
